### ISSUE TITLE
Update RSS feed to support more than 10 episodes

### ISSUE THREAD

**Issue by monomo111** [10up/simple-podcasting#103]
Hi

On my Website I have and podcast with well over 50 Episodes.
But only the last 10 Episodes are in the RSS Feed.
Can I somehow chance something so all or more Episodes are in the RSS Feed?

Maybe you can add this as a option for everybody.

**Comment by jeffpaul** [comment]
@monomo111 try changing the WordPress setting at `Settings` > `Reading` and adjusting `Syndication feeds show the most recent` to be the number you want included in feeds.

<img width="1062" alt="Screen Shot 2021-02-09 at 2 48 03 PM" src="https://user-images.githubusercontent.com/2818133/107426799-4eae4c00-6ae6-11eb-9adc-9448575bfa60.png">

**Comment by jeffpaul** [comment]
@monomo111 are you still seeing an issue here after changing that WP setting?

**Comment by jeffpaul** [comment]
@monomo111 after reviewing the [Apple Podcast spec](https://itunespartner.apple.com/podcasts/articles/podcast-requirements-3058), it looks like their only requirement is that a podcast feed includes at least one episode with no upper bounds.  As such, I'm going to update this issue and label it as an `enhancement` for our next release with the general approach:
- [ ] update feed to include 250 episodes per page
- [ ] new filter for developers to override this for any edge cases we haven't anticipated
- [ ] update readme to note this new episode feed setting and related filter

props @jakemgold for the approach on this
