### ISSUE TITLE
Add ability to remove audio file from Podcast block without having to delete entire block

### ISSUE THREAD

**Issue by jeffpaul** [10up/simple-podcasting#104]
**Is your enhancement related to a problem? Please describe.**
In testing #102, David Chabbi came across the following:
> There is also no option to remove the file once you have uploaded. You have to delete the whole block. Not just remove the podcast.

**Describe the solution you'd like**

**Designs**

**Describe alternatives you've considered**

**Additional context**

**Comment by dinhtungdu** [comment]
I can confirm the behavior this issue mentioned and #107 fixes this.

But do we need to delete the file without deleting the block? Why do we want to have an empty block without a podcast file? IMO we don't.

cc @helen.

**Comment by jeffpaul** [comment]
@dinhtungdu I suppose the case this could be supporting is adding an incorrect audio file and wanting to remove it without removing any additional description/etc. added to the block?

**Comment by dinhtungdu** [comment]
> adding an incorrect audio file and wanting to remove it without removing any additional description/etc. added to the block?

@jeffpaul I would 1) remove the block or 2) replace the incorrect audio with the correct audio file in that case.

We have a `figcaption` for podcast file caption, but it sticks with the podcast file, it doesn't make sense to me to keep that caption after removing the podcast.

**Comment by jeffpaul** [comment]
@dinhtungdu so maybe close this issue and #107 as `invalid`?

**Comment by dinhtungdu** [comment]
> @dinhtungdu so maybe close this issue and #107 as `invalid`?

Yes. I agree.

**Comment by jeffpaul** [comment]
I'm closing this issue and related PR after our additional discussion has determined that the original report fell short in identifying an intended or valid use case of our expected plugin audience.  If you feel our assessment is in error, please feel free to re-open this issue and share your reasoning.  And thanks to @Firestorm980 for his work on attempting to resolve this issue, your contribution is still very much appreciated!
