### ISSUE TITLE
Podcast block Upload button doesn't work, you need to to re-select the uploaded file in the Media Library

### ISSUE THREAD

**Issue by jeffpaul** [10up/simple-podcasting#105]
**Describe the bug**
Issues identified by David Chabbi in testing Simple Podcasting 1.2.0 on WordPress 5.6 in #102:
> Wouldn't work when I tried to upload a file direct from Gutenberg editor. Only once I had uploaded media library and then selected the audio file did the file appear. When I tried to upload using the following button nothing happened. I selected the file and then was brought back to the page with no audio file inserted.

![unnamed](https://user-images.githubusercontent.com/2818133/108419303-f79c2b80-71f7-11eb-9d04-d0e73c66b1b8.png)

**Steps to Reproduce**

**Expected behavior**

**Screenshots**

**Environment information**
 - Device: 
 - OS: 
 - Browser and version: 
 - WordPress version: 
 
 - Plugins and version: 
 - Theme and version: 
 
 - <details><summary>Site Health Info:</summary>
   
   </details>

**Additional context**

**Comment by Firestorm980** [comment]
@jeffpaul I looked at this one and I haven't been able to reproduce yet. With the Twenty Twenty One theme on WP 5.6.2 I was able to:

- Upload using the button in the UI
- Drag and drop a file from my finder into the block

Might have to connect with David to get some additional information or context.

**Comment by jeffpaul** [comment]
@Firestorm980 yeah, in trying to read the text of the error message (its rather pixelated) I wonder if the filetype of the media upload was one that WP by default does not allow?

**Comment by Firestorm980** [comment]
@jeffpaul I was able to get some additional information from David. He gave this screen recording of it not working. Looks like a .m4a file.

https://user-images.githubusercontent.com/8181366/109977102-156e9380-7cc2-11eb-82b9-9c676ef4edaf.mov

**Comment by jeffpaul** [comment]
@Firestorm980 ok so it looks like the m4a file gets successfully uploaded, but not shown within the podcast block until he goes in and selects it from the media library.  I'll update the issue title accordingly and we can look into why the file isn't showing in the block the first time around.

**Comment by Firestorm980** [comment]
@jeffpaul This may actually be related to a current core issue. Here's the trail I had through the Gutenberg project:
https://github.com/WordPress/gutenberg/issues/14174
https://github.com/WordPress/gutenberg/issues/9028
https://core.trac.wordpress.org/ticket/40175

**Comment by cadic** [comment]
Not able to reproduce this.

But I've faced exact the same issue with WordPress core **Image Block** today:
- Upload button does nothing
- No debug/error output to the console related to upload button click
- Media explorer workaround works

The issue was resolved after Chrome cold restart (hold cmd+Q and reopen). Looks like this is browser-related issue.
