### ISSUE TITLE
There are no more mp3 or Audio file detected from Post content after lastest WordPress update

### ISSUE THREAD

**Issue by channchetra** [10up/simple-podcasting#123]
Normally we just add audio file through Podcast Block with with Podcast Taxonomy checked it will auto generated in feed but now the feed are generated but only text there are no audio <enclosure> detected.

**Comment by jeffpaul** [comment]
Relates to #111

**Comment by pabamato** [comment]
Hi @channchetra , thank you for reporting.
I was not able to replicate the issue using several WordPress core versions and simple-podcasting (v1.2.0 and sourced from develop branch).
Could you please provide additional details for replicating the issue? WordPress core version, plugin version, and if possible the feed output would be great.

Thank you.
