### ISSUE TITLE
is_feed called too early

### ISSUE THREAD

**Issue by tomjn** [10up/simple-podcasting#134]
### Describe the bug

After updating to the latest version 1.2.1 we're seeing this issue:

```
is_feed was called incorrectly. Conditional query tags do not work before the query is run. Before then, they always return false. Please see Debugging in WordPress for more information. (This message was added in version 3.1.0.)
```

For reference the plugin is installed via composer and loaded in an MU plugin file

### Steps to Reproduce

1. Use the plugin
2. Run WP CLI or load a page and inspect for PHP notices

### WordPress information

WP 5.8

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by tomjn** [comment]
https://github.com/10up/simple-podcasting/blob/develop/simple-podcasting.php#L114

```
	if ( is_feed() && is_tax( TAXONOMY_NAME ) ) {
```

It should instead be:

```
	if ( $query->is_feed() && $query->is_tax( TAXONOMY_NAME ) ) {
```

With the query variable added to the function parameters and the hook addition updated accordingly

**Comment by jeffpaul** [comment]
@tomjn thanks for flagging this, I've tagged @cadic for review.
