### ISSUE TITLE
Block: Podcast Services

### ISSUE THREAD

**Issue by jeffpaul** [10up/simple-podcasting#154]
### Is your enhancement related to a problem? Please describe.

Many podcast sites like to promote all the various podcast services where they syndicate their content (e.g., Pocket Casts, Apple Podcasts) on their homepage and within individual episode posts.  There's currently no way to do this in the core Social Icons block nor any other quick way to do this using Simple Podcasting.  So I propose a block that would allow a site owner to enable/disable the various podcast services and which would provide a visual icon for each of those enabled services.  Open to what we call the block, "Podcast Services" doesn't feel quite right but is the best I can quickly come up with right now.

The following appear to be a good listing of podcast services to include:
- Pocket Casts
- Apple Podcasts
- Google Podcasts
- Stitcher
- PlayerFM
- Overcast
- Pandora
- Castro
- TuneIn
- Spotify
- RSS (for the actual RSS feed of the podcast to be subscribed to in some other manner)

We'll probably want to include these services as new fields in the [podcast settings](https://github.com/10up/simple-podcasting/blob/develop/.wordpress-org/screenshot-3.png) so that the links to the podcast on each service is stored there and called into the block display for actual icon links.

Here's a good listing of the icons to use for each service (see "Player Icon Set"): https://www.podpage.com/badges/.  As shown on the [Apple Podcasts Identity Guidelines page](https://www.apple.com/itunes/marketing-on-podcasts/identity-guidelines.html#apple-podcasts-icon), it might be nice to have black icons and white icons created from the full color versions on podpage.com and allow a site owner to chose from a full color, black, or white icon set for the display in the block.

### Designs

Example icon display from [WP Briefing](https://wordpress.org/news/2022/02/episode-25-five-cents-on-five-for-the-future/):
![Screen Shot 2022-03-02 at 1 37 29 PM](https://user-images.githubusercontent.com/2818133/156436606-18dbfde4-91de-4823-8722-0bd9bea76f11.png)

### Describe alternatives you've considered

Await initial inclusion of these services in the core Social Icons block: https://github.com/WordPress/gutenberg/issues/36755.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jeffpaul** [comment]
@cadic not sure if you feel this is worth milestoning into 1.4.0 or a future 1.5.0 release?

**Comment by cadic** [comment]
@jeffpaul let's keep it in 1.4.0 along with other podcast blocks, I know @Sidsector9 already started with one of these.

**Comment by KajiiNarumi** [comment]
it would be enough to be able to add our own icons and services in the social link widget

**Comment by jeffpaul** [comment]
Available sample icons (color, black, white) here: https://drive.google.com/drive/folders/1gJSLI9iXcLpQ___a0A7WQWXVL_uPsEgt.  Noting that's a 10up internal link, so if someone outside 10up is interested in a PR for this I can ZIP those up and post directly to this issue.  Credit for that imagery should go to [Stephanie Campbell (@sncampbell)](https://github.com/sncampbell).

**Comment by jeffpaul** [comment]
Noting that @achchu93 is looking into this issue.

**Comment by jeffpaul** [comment]
@achchu93 are you still tracking work on this such that you can push up a PR or should I look to pull 10upper availability to help on a PR?

**Comment by Sidsector9** [comment]
@jeffpaul I'll raise the PR by today or tomorrow

**Comment by Sidsector9** [comment]
## Progress update

### Term meta settings for podcast platforms

<img width="1392" alt="Screenshot 2022-11-22 at 8 15 22 PM" src="https://user-images.githubusercontent.com/17757960/203343554-30ac68fc-da79-4c65-a7ca-0f322836e732.png">

Gutenberg Block is ready in the editor, finalising the frontend output.


### Bonus features to add

- Ability to reorder platforms

**Comment by Sidsector9** [comment]
## Progress Update

### Simple block implementation

#### Black

<img width="652" alt="Screenshot 2022-11-23 at 1 20 22 PM" src="https://user-images.githubusercontent.com/17757960/203495544-f4e65873-b86e-40ce-9361-943f813e67d4.png">

#### Color

<img width="638" alt="Screenshot 2022-11-23 at 1 21 54 PM" src="https://user-images.githubusercontent.com/17757960/203495596-83de4d5d-7a79-4305-ad38-004a8b6ca153.png">

**Comment by Sidsector9** [comment]
@jeffpaul This block can have some few controls for customisation:

- Icon size control
- Layout options: linear | grid

@10up/open-source-practice have any thoughts on this?

**Comment by jeffpaul** [comment]
I'm fine with no-to-minimal controls at first and ones can be added based on community input.

**Comment by jeffpaul** [comment]
Noting that once this is released we'll want to assess if there are additional services that should be added, as I believe Amazon Music now includes podcasts and there may be others but will await community feedback before we iterate.
