### ISSUE TITLE
Test against WordPress 6.0

### ISSUE THREAD

**Issue by vikrampm1** [10up/simple-podcasting#165]
Is your enhancement related to a problem? Please describe.
Once WordPress 6.0 is released, we'll want to test Simple Podcasting to see if any incompatibility issues arise.

Describe the solution you'd like

- [ ] test Simple Podcasting on WordPress 6.0
- [ ] open issues for any incompatibilities noted in testing
- [ ] resolve issues identified in testing
- [ ] bump "tested up to" version
- [ ] if code changes needed due to incompatibilities, ship a plugin release, otherwise use "Plugin asset/readme update" action to update "tested up to" version on .org repo

Designs
n/a

Describe alternatives you've considered
none

Additional context
Related: #137, #111, #108,  #98, #80

**Comment by cadic** [comment]
The 6.0-beta was included in our Cypress tests for last few months and passing all tests successfully since then.
