### ISSUE TITLE
Add Subcategories

### ISSUE THREAD

**Issue by dchucks** [10up/simple-podcasting#173]
### Is your enhancement related to a problem? Please describe.

It would be useful to add sub-categories for each category chosen for a Podcast. The full list is at https://podcasters.apple.com/support/1691-apple-podcasts-categories. 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jeffpaul** [comment]
@dchucks the 3 category dropdowns already have subcategories as options within them, but it looks like some of these have changed over time so we can look to update the options to match the apple spec.  Was there anything else you had in mind on this or would that suffice?

**Comment by dchucks** [comment]
You are right @jeffpaul, I meant a sync with the latest Specification to refresh the list. Thanks.

**Comment by jeffpaul** [comment]
@zamanq are you still working on a PR for this or should I unassign so someone else can pickup the work?

**Comment by zamanq** [comment]
> @zamanq are you still working on a PR for this or should I unassign so someone else can pickup the work?

@jeffpaul Yes I'm working on it.
