### ISSUE TITLE
Incorrect Language value in feeds?

### ISSUE THREAD

**Issue by dchucks** [10up/simple-podcasting#174]
### Describe the bug

IMHO the value for the "Language" tag in the feed should be in format <lang-ISO-Code>-<Country Code> e.g. en-US, but presently an underscore (_) is being used instead of a hyphen (-), e.g. **hi_IN** while it should be **hi-IN** instead. I have seen some platforms (like Jio Saavn) unable to read the language due to this bug and default to English.

### Steps to Reproduce

Please look at the "Language" field under parent "Channel" in the generated feed.

### Screenshots, screen recording, code snippet

Example from my feed:
![image](https://user-images.githubusercontent.com/1902537/168483953-8bd27aea-649b-4614-862c-d876b849e139.png)

### Environment information

Win10 OS, Chrome

### WordPress information

Wordpress 5.9.3, PHP 7.4, Audioman theme, Simple Podcasting v1.2.3.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by cadic** [comment]
@dchucks thank you for reporting this!

Correct, from a [Podcaster’s Guide to RSS](https://help.apple.com/itc/podcasts_connect/#/itcb54353390), they expect <language> to be an [ISO 639](https://www.loc.gov/standards/iso639-2/php/code_list.php) code.

> (two-letter language codes, with some possible modifiers, such as "en-us")
