### ISSUE TITLE
Bump WordPress and PHP minimums

### ISSUE THREAD

**Issue by vikrampm1** [10up/simple-podcasting#178]
Bump WP & PHP Minimums to the following
 
- [x] WordPress to 5.7
- [x] PHP to 7.4
- [x] Remove any no-longer-needed conditional code for older version support.
- [x] Take a look at adjusting our testing matrices, if applicable.
- [x] Bump the minimums in plugin documentation and header fields.

**Comment by peterwilsoncc** [comment]
I've switched this to a bug as I discovered while testing #41 that the block is incompatible with WP versions 5.0 - 5.3. Once #183 is merged it will require 5.7+ 

**WordPress 5.0**
![Screen Shot 2022-09-16 at 9 44 25 am](https://user-images.githubusercontent.com/519727/190527393-3d09618d-30d1-47b6-98b3-c45f088735f1.png)

**WordPress 5.2**
![podcast-52](https://user-images.githubusercontent.com/519727/190527626-cba6bc18-ef01-464f-a95a-be19281de747.gif)

**WordPress 5.3**
![Screen Shot 2022-09-16 at 9 49 18 am](https://user-images.githubusercontent.com/519727/190527812-dea0c536-a8d3-4e0e-b995-5d651d915e8f.png)
