### ISSUE TITLE
Player enhancements

### ISSUE THREAD

**Issue by jeffpaul** [10up/simple-podcasting#191]
### Is your enhancement related to a problem? Please describe.

The existing player that is used with the plugin is the default core audio player with no additional enhancements even with various toggles/metadata set in the podcast block settings:
![Screen Shot 2022-10-20 at 10 27 00 AM](https://user-images.githubusercontent.com/2818133/196991754-61c5e3c2-8bcd-498a-b70c-6ee861323f5e.png)

It might be nice to enhance the player to support the following functions:
- [ ] Display show title
- [ ] Display episode title
- [ ] Display show image/icon
- [ ] Display explicit badge if content marked as explicit
- [ ] Display season number
- [ ] Display episode number
- [ ] Display episode type
- [ ] #298 
- [ ] #299 
- [ ] #303 

Open to any/all of these items to roll into their own PR, best to update each item above with any linked PR # at the end of the line to better track completion of the work.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jeffpaul** [comment]
@Sidsector9 I'm unassigning you here as there doesn't appear to be a WIP PR, so moving this out for others to pick up and work on

**Comment by jeffpaul** [comment]
Some good examples in https://wordpress.org/plugins/podcast-player/

**Comment by jayedul** [comment]
> best to update each item above with any linked PR # at the end of the line

@jeffpaul I think implementing the whole checklist in a single PR will be more maintainable. Because these content's should be organized in a single wrapper element and design structure.

**Comment by jeffpaul** [comment]
@jayedul if you've got the time and interest, go for it!

**Comment by jeffpaul** [comment]
Another good example: https://portlandartmuseum.org/podcast/black-artists-of-oregon-episode-1/

![Screenshot 2023-09-13 at 10 36 48 AM](https://github.com/10up/simple-podcasting/assets/2818133/f39b34f6-dd44-4225-9b52-a4591a7f71e1)

**Comment by gusaus** [comment]
Quick followup on the [prior art](https://10up.com/blog/2016/wamu-react-rest-api/) on [WAMU's site](https://wamu.org/) referenced in https://github.com/10up/simple-podcasting/issues/299

In addition to the player being persistent, the ability to play on-demand podcasts AND live radio streams is key. Not sure if that would make sense for a plugin focused on podcasting, but possibly as a stand-alone persistent audio player?

Either way, we'd like to include the plugin and the persistent player(s) in the Newspack branches maintained by OpenProducer (see https://github.com/OpenProducer/newspack-radio-pro/issues/3) and would love to contribute/help where we can.
