### ISSUE TITLE
<itunes:summary> is deprecated?

### ISSUE THREAD

**Issue by cadic** [10up/simple-podcasting#206]
### Describe your question

In the RSS channel header we have `<itunes:summary>` field which is not described in the current Apple documentation

While on some old articles, this field looks like a predecessor of the current `<description>` field

https://www.feedforall.com/itune-tutorial-tags.htm#summary

> **<itunes:summary>**
At the Channel level, this tag is a long description that will appear next to your Podcast cover art when a user selects your Podcast. At the Item level, this tag is a long description that will be displayed in an expanded window when users click on an episode. Limited to 4000 characters or less, plain text, no HTML

Looks similar to how the current [Apple documentation](https://help.apple.com/itc/podcasts_connect/#/itcb54353390) describes the `<description>` field:

> Where description is text containing one or more sentences describing your podcast to potential listeners. The maximum amount of text allowed for this tag is 4000 bytes.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jeffpaul** [comment]
I'd be fine with updating from one field to the next, nice catch @cadic!
