### ISSUE TITLE
Create podcast show in onboarding gives "Invalid taxonomy" error.

### ISSUE THREAD

**Issue by iamdharmesh** [10up/simple-podcasting#246]
### Describe the bug

Creating a podcast show in the onboarding first step gives an "Invalid taxonomy" error.

```
PHP Warning:  Use of undefined constant TAXONOMY_NAME - assumed 'TAXONOMY_NAME' (this will throw an Error in a future version of PHP) in /Users/******/public/wp-content/plugins/simple-podcasting/includes/create-podcast.php on line 128
```

It seems this issue is related to recent PR #238 in which we renamed Constant TAXONOMY_NAME to PODCASTING_TAXONOMY_NAME and need to update the constant to PODCASTING_TAXONOMY_NAME here.
https://github.com/10up/simple-podcasting/blob/f67700410c4de5c447268cd3bbf4106716ed75ac/includes/create-podcast.php#L126-L129

### Steps to Reproduce

1. Activate the plugin for the first time on site or update the `simple_podcasting_onboarding` option to `no`, if it is already in use on site.
2. Feel a podcast show details on onboarding and click on create.
3. Notice that create podcast failed and the "Invalid taxonomy" error is shown.

### Screenshots, screen recording, code snippet

<img width="1338" alt="image" src="https://github.com/10up/simple-podcasting/assets/10613171/301a190b-5d7a-4a4a-b8ed-2b2636930c0f">

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by kmgalanakis** [comment]
PR here: https://github.com/10up/simple-podcasting/pull/247
