### ISSUE TITLE
Unique Cover Art for Episodes

### ISSUE THREAD

**Issue by jamesburgos** [10up/simple-podcasting#255]
### Is your enhancement related to a problem? Please describe.

I love the simplicity of this plugin, it definitely works as advertised. In the spirit of keeping it that way, I think the ability to add a unique cover art image to an individual episode would be useful as part of the core feature set. A show's cover art would alway take precedent to the episode's cover art when viewed in the podcast directories, but if the episode has its own art, this art would display on the users device when the episode is playing.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jeffpaul** [comment]
@jamesburgos do you know offhand if the podcast spec supports unique art at the episode level versus just inheriting the show art?

**Comment by jamesburgos** [comment]
Thank you Jeff for your timely response. Me, on the other hand, I missed the notification, so here we are 3 weeks later, doh.

Anyway, I'm not a developer but I play one on the web. That said, here's what I know.

The <image> element from which channel art is typically referenced is one of the base elements included in the [official RSS 2.0 spec from 07/15/03](https://cyber.harvard.edu/rss/rss.html#ltenclosuregtSubelementOfLtitemgt). According to the spec, developers can extend RSS and create new modules or elements but must do so in the form of a namespace.

> “A RSS feed may contain elements not described on this page, only if those elements are defined in a namespace.”

I always assumed (until you asked) that episode cover art was universally supported between podcast publishing apps and podcast player apps. Upon searching , it seems that support for episode art is mixed, and was most notably absent, until recently, in the Apple Podcasts app. The just released iOS 17 [now supports episode artwork](https://podcasters.apple.com/5303-ios-17-whats-new-apple-podcasts) in the Podcasts app. I'm sure any remaining podcast players that currently do not will soon support it as well.

Here's and article on [creating namespaces](https://www.disobey.com/detergent/2002/extendingrss2/).

I hope you can implement this into Simple Podcasting sooner than later. I have several projects in the pipeline that would benefit from having this. There are lots of use cases for it. Multi-season serial podcasts, for example, will be able to brand each season with its own unique art. I've seen some publishers split their seasons into separate feeds to create visual distinction but can you imagine the nightmare it must be to get listeners to resubscribe.

Thanks again, Jeff.
