### ISSUE TITLE
Issue with Displaying All Podcasts in Gutenberg Editor on WordPress 6.4.2

### ISSUE THREAD

**Issue by channchetra** [10up/simple-podcasting#267]
### Describe your question

Hello Community,

I'm encountering an issue with the Gutenberg editor in WordPress 6.4.2 where only 10 of my podcast categories are displayed, despite having 18 in total. Specifically, in the Gutenberg post editor, the taxonomy selector for my custom taxonomy (podcasts) is not showing all the available terms. It lists only 10 podcasts without providing a search box to access the others.

Here are some details about my setup:

WordPress version: 6.4.2
Custom taxonomy: _podcasting_podcasts_
Total terms in the taxonomy: 18
Issue: Gutenberg editor displays only 10 terms without a search option
I've tried modifying the REST API query parameters to increase the number of terms returned, and while the REST API endpoint `wp-json/wp/v2/podcasting_podcasts` successfully lists all the terms, these changes don't seem to be reflected in the Gutenberg editor.

Could anyone provide insights or solutions on how to ensure that all taxonomy terms are displayed in the Gutenberg editor, along with a search functionality? Any advice or guidance would be greatly appreciated.

Thank you in advance for your help!

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by dkotter** [comment]
@channchetra Thanks for the report. This is indeed a bug and I've opened #268 to resolve this. If you have some time to test out that PR and ensure it fixes things for you, that would be great. Thanks!

**Comment by channchetra** [comment]
Hello @dkotter ,

I have tested your recent PR and am pleased to report that it's working as expected. The issue I was experiencing has been resolved. Thank you for your efforts in addressing this problem.
