### ISSUE TITLE
Saving & Retrieving Podcast Summary

### ISSUE THREAD

**Issue by uamv** [10up/simple-podcasting#34]
When creating/editing a podcast the summary field does not save the value to `podcasting_summary` in `wp_termmeta`.

Also, after manually entering a value for `podcasting_summary`, this value is not retrieved and inserted into the textarea input on the Edit Podcast screen.

**Comment by helen** [comment]
Looks like something about minification causes this issue, fix incoming.

**Comment by helen** [comment]
Hi @uamv, thanks for the bug reports. I figured out the issue with displaying the stored value but I can't seem to reproduce the issue where it doesn't save. Could you double check to be sure that storage was an issue and not just the display? Thanks!

**Comment by uamv** [comment]
Ah, you are correct. It does seem to be storing properly for me. Glad you were able to identify the display issue. Thanks!

**Comment by helen** [comment]
Okay great, thanks for the confirmation!
