### ISSUE TITLE
Podcast Image Does Not Save

### ISSUE THREAD

**Issue by uamv** [10up/simple-podcasting#35]
When creating/editing a podcast the image field does not fill a value after having opened the media modal and choosing a selected image. Instead, the console throws an error.

<img width="680" alt="simple-podcasting-image-error" src="https://user-images.githubusercontent.com/6343951/42121939-513e833e-7c07-11e8-9ad8-32baa58154b7.png">

After manually entering values into the database for `podcasting_image_url` and `podcasting_image`, the values are retrieved and displayed properly, but can not be edited from the Edit Podcast screen.

**Comment by helen** [comment]
Looks like something about minification causes this issue, fix incoming.
