### ISSUE TITLE
Improve onboarding experience - (phase 1)

### ISSUE THREAD

**Issue by helen** [10up/simple-podcasting#40]
Right now you still need to read the docs (which are already slightly outdated) to figure out that you need to set up at least one podcast term in order for podcasting functionality to be available in the editor. We should consider the following as a better onboarding experience:

* An admin notice if the plugin has been activated but no term has been set up yet (we should be wary of notice fatigue). This could be admin-wide or on specific pages. There is currently one on the taxonomy list/add screen.
* Allowing a podcast term to be added while in the editor, and then handle the fact that it needs more metadata set before actually going live somehow (notice, modal to edit all those details, something else).

Other ideas?

**Comment by jeffpaul** [comment]
Thanks to @Nicolas-knight for a [Miro board](https://miro.com/app/board/uXjVPZ_WdrI=/?moveToWidget=3458764532986673769&cot=14) with recommendations on how to improve things here and a [Figma prototype](https://www.figma.com/proto/rvYiiSxMdBzrPx7xmnCFgv/Simple-Podcasting-Plugin?page-id=2%3A17&node-id=14%3A73&viewport=346%2C184%2C0.15&scaling=scale-down-width&starting-point-node-id=14%3A73) exploring some of the onboarding ideas and other miscellaneous improvements.  Noting that if I'm able to get more of Nicolas' time that we'll look to add wireframes for the podcast management page with some ideas for dealing with "a wall of fields" issue as exists in the plugins admin screen currently.

**Comment by jeffpaul** [comment]
Additional thanks to @jnetek for a [continued Figma investigation](https://www.figma.com/file/rvYiiSxMdBzrPx7xmnCFgv/Simple-Podcasting-Plugin) on potential UX improvements for the plugin.

**Comment by Sidsector9** [comment]
## Progress:

The 'view' part of the onboarding pages is implemented:

### Step 1:

<img width="1792" alt="Screenshot 2022-10-26 at 9 13 57 PM" src="https://user-images.githubusercontent.com/17757960/198072853-d15a20cd-53e4-47f7-bfb3-1a6c875fb6fd.png">

### Step 2:

<img width="1792" alt="Screenshot 2022-10-26 at 9 14 12 PM" src="https://user-images.githubusercontent.com/17757960/198072927-b407ffed-c6c8-4dc2-bf80-3153548bcd88.png">

### Next step:

Implement the functionality for the buttons.
