### ISSUE TITLE
Gutenberg: external URL field no longer shows

### ISSUE THREAD

**Issue by helen** [10up/simple-podcasting#43]
This is pretty bad if you're trying to edit an existing external URL podcast because it leaves you without a way to cancel outside of refreshing the entire page. This seems to have happened in a relatively recent Gutenberg update.

**Comment by ryanwelcher** [comment]
@helen look like this was a change to the prop name name logic that allow for either naming convention - https://github.com/WordPress/gutenberg/commit/e95026cee0d66b98d8b4e958cfacf8fe9a9e8b2d#diff-56d6af193779467f7a4cb10e85c26ef3L123
