### ISSUE TITLE
Specify podcast language

### ISSUE THREAD

**Issue by larkov** [10up/simple-podcasting#54]
Right now the podcast feed language is set to the language of the WordPress site.

If you have a site that is set up with the language english but the podcast is in Swedish the feed information will be wrong.

**Comment by helen** [comment]
Makes sense, will look into adding the setting. Are you interested in making a PR?

**Comment by larkov** [comment]
I'll try to make PR for it but probably not this week.

**Comment by helen** [comment]
No problem, I'd like to get a release out early next week and I think it would make sense to include this so we'll likely work on a fix.
