### ISSUE TITLE
Specify email tag in feed

### ISSUE THREAD

**Issue by larkov** [10up/simple-podcasting#55]
It would be nice to be able to specify <googleplay:email> OR <itunes:email> tag temporarily so that you add your feed to Google Play Music Podcast Portal. The email tag is mandatory when adding a new podcast there.

**Comment by helen** [comment]
Hi! Does this need to be temporary or should it really be a regular setting for each podcast the way title, genre, etc. are? And further, does it make sense to fall back to the admin email for the site or should it be specifically set for each podcast?

**Comment by larkov** [comment]
It doesn't need to be temporary but for google it is only mandatory when submitting a podcast to them, after that it could be removed.
As for the email adress it's not always the administrator for the site that sets up the podcast so to be able to edit the email adress would be preferable.

**Comment by helen** [comment]
> As for the email adress it's not always the administrator for the site that sets up the podcast so to be able to edit the email adress would be preferable.

Sure, I just mean to use the admin email if no other email address has been entered.

**Comment by ryanwelcher** [comment]
@larkov Would it be acceptable to have both `googleplay:email` and `itunes:email` tags in the feed?

**Comment by ryanwelcher** [comment]
According to https://support.google.com/googleplay/podcasts/answer/6260341#series - it looks like we can use the iTunes tags and they will be supported.
