### ISSUE TITLE
Gutenberg: "Cancel" out of block editing mode

### ISSUE THREAD

**Issue by helen** [10up/simple-podcasting#62]
The edit icon allows you to change the URL or select a new podcast; however, there's no way to keep your current selection and go back to the preview mode without selecting your item all over again. There should be a cancel button and possibly also an indicator of what the current selection is so you understand that the selection hasn't been lost/won't change until you choose something else.

**Comment by Firestorm980** [comment]
@helen @jeffpaul 

Here's a screenshot of WIP branch I have for this of the block in editing mode. The "Cancel" button and message will only show in edit mode if there is a source currently assigned to the block. Additionally, the edit button turns into a "Cancel" button as an alternative method to go back.

Let me know your thoughts on this approach.

<img width="806" alt="simple-podcasting-issue-62_wip-r1" src="https://user-images.githubusercontent.com/8181366/79030635-99c2a000-7b5f-11ea-91f6-8f09a5d14b18.png">

**Comment by Firestorm980** [comment]
@helen @jeffpaul I also found in my research of the core audio block, that it handles editing this with a `MediaReplaceFlow` in the `BlockControls` component for the block. This may be a better alternative to maintain consistency with core. Appreciate thoughts you may have.

**Comment by Firestorm980** [comment]
@helen @jeffpaul Example using `MediaReplaceFlow`. When the block doesn't have anything attached it shows as it currently does.

<img width="621" alt="Screen Shot 2020-04-17 at 1 06 21 PM" src="https://user-images.githubusercontent.com/8181366/79600149-4cd55100-80ac-11ea-964b-04bf10a8244d.png">
