### ISSUE TITLE
Block Pattern: Latest Episode Block

### ISSUE THREAD

**Issue by jeffpaul** [10up/simple-podcasting#83]
**Is your enhancement related to a problem? Please describe.**
With the advent of [Block Patterns](https://wptavern.com/block-patterns-will-change-everything), we might want to consider a simple block pattern to cover the Latest Episode Block concept.

**Describe the solution you'd like**

- [ ] Pulls in latest episode automatically, might have some options for setting image override, etc but essentially will get all data from podcast.

**Designs**

TBD, but ideal to help shape what we'd craft

**Describe alternatives you've considered**

n/a

**Additional context**

[Block Pattern creation walkthroughs](https://melchoyce.design/2020/03/30/creating-a-simple-block-pattern-plugin-for-the-gutenberg-editor/) from the super rad @melchoyce.

**Comment by jeffpaul** [comment]
This might be easier to accomplish now with the Query Loop block likely capable for handling most of this.

**Comment by cadic** [comment]
Wireframes for Latest Podcast block: https://www.figma.com/file/14KjviZcFQZ1H6bIhSPwXa/Podcast-Block-Patterns?node-id=1%3A35

Credits: Nickolas Kola

**Comment by jeffpaul** [comment]
Note that the Query Loop block can likely handle this functionality now, so likely worth bumping this in priority on the roadmap: https://make.wordpress.org/core/2022/02/03/whats-new-in-gutenberg-12-5-february-2nd/#query-loop-custom-taxonomies-filtering-and-more

**Comment by Sidsector9** [comment]
## Progress update:

I've used the Query loop block to create a custom pattern called "Latest Episiode":

### Editor

<img width="1680" alt="Screen Shot 2022-03-04 at 12 14 58 AM" src="https://user-images.githubusercontent.com/17757960/156631567-435c5845-ddd8-4681-a211-50470a886f97.png">

### Frontend

<img width="1680" alt="Screen Shot 2022-03-04 at 12 16 36 AM" src="https://user-images.githubusercontent.com/17757960/156631773-1dabbd28-6c98-4085-af51-57d795087393.png">

**Comment by Sidsector9** [comment]
OSP standup feedback and questions:

- Default behavior if Post doesn't have a featured image.
- Does group have a setting to set background color?

**Comment by Sidsector9** [comment]
> Default behavior if Post doesn't have a featured image.

The group has a default background color which will be shown.

> Does group have a setting to set background color?

Yes. As answered above.

**Comment by jeffpaul** [comment]
FYI, potentially related: [Extending the Query Loop block](https://make.wordpress.org/core/2022/10/10/extending-the-query-loop-block/) dev note from WP 6.1.

**Comment by jeffpaul** [comment]
@Sidsector9 are you still tracking work on this such that you can push up a PR or should I look to pull 10upper availability to help on a PR?

**Comment by Sidsector9** [comment]
@jeffpaul this pattern longer works with the changes in WordPress. I am investigating this at the moment.
