### ISSUE TITLE
Block Pattern: Post Grid Block

### ISSUE THREAD

**Issue by jeffpaul** [10up/simple-podcasting#84]
**Is your enhancement related to a problem? Please describe.**
With the advent of [Block Patterns](https://wptavern.com/block-patterns-will-change-everything), we might want to consider a simple block pattern to cover the Post Grid Block concept.

**Describe the solution you'd like**

- [ ] Output grid of episode posts with simple options for how many to render (2,4,6)

**Designs**

TBD, but ideal to help shape what we'd craft

**Describe alternatives you've considered**

n/a

**Additional context**

[Block Pattern creation walkthroughs](https://melchoyce.design/2020/03/30/creating-a-simple-block-pattern-plugin-for-the-gutenberg-editor/) from the super rad @melchoyce.

**Comment by jeffpaul** [comment]
This might be easier to accomplish now with the Query Loop block likely capable for handling most of this.

**Comment by ajmaurya99** [comment]
Hey @jeffpaul 

In my understanding Block Patterns are used for the static content blocks, In our case we need something dynamic to fetch the latest three post with the Podcast taxonomy.

In this case we wont be able to use the Query Loop block also, Currently Query Loop block doesn't support custom taxonomies. It would say its still early for us to use Block Patterns in this case.

We have a few open issues in Gutenberg repo regarding adding support for custom taxonomies. It would be worth waiting for it.

https://github.com/WordPress/gutenberg/issues/34977
https://github.com/WordPress/gutenberg/issues/30706
https://github.com/WordPress/gutenberg/issues/26304

Alternative, if we really want to ship something with Block Patterns then we need to develop a custom block to fetch latest posts with the Podcast Taxonomy.

**Comment by jeffpaul** [comment]
@ajmaurya99 thanks for the research notes, that's very helpful!  I would say in general it would probably be best to wait until the Query Loop block (or some other core block) is able to help solve for this issue as the need for the Post Grid block for this plugin is fairly basic in nature and once CPTs work in the Query Loop block would easily cover our needs here.

**Comment by cadic** [comment]
Wireframes for Post Grid Block: https://www.figma.com/file/14KjviZcFQZ1H6bIhSPwXa/Podcast-Block-Patterns?node-id=1%3A70

Credits: Nickolas Kola

**Comment by jeffpaul** [comment]
Note that the Query Loop block can likely handle this functionality now, so likely worth bumping this in priority on the roadmap: https://make.wordpress.org/core/2022/02/03/whats-new-in-gutenberg-12-5-february-2nd/#query-loop-custom-taxonomies-filtering-and-more

**Comment by jeffpaul** [comment]
Noting that @achchu93 is looking into this issue.

**Comment by achchu93** [comment]
As per the Figma design, there is a placeholder for duration. I identified going with a custom block for duration meta is the best practices. But now the question is, whether we gonna make a block which can pull the value with meta name or specifically fetch the value of duration meta. Need suggestion on this.

**Comment by jeffpaul** [comment]
@cadic any thoughts on ^ this question?

**Comment by cadic** [comment]
@achchu93 the episode duration is stored in `podcast_duration` post meta. It is fetched automatically from the media file when adding the episode. It also could be overriden in a podcast block at a single post. I don't feel we need another place to override the duration. Let's just take the value from the post meta.

**Comment by cadic** [comment]
Since the stored value `12:34` is different than displayed `12 min`, I think it's better to have a custom block "Podcast Duration" which will only display the duration meta (converted from `MM:SS` to `.. hr .. min`)

**Comment by jeffpaul** [comment]
@achchu93 are you still working on a PR for this or should we unassign so someone else can pick up the issue?

**Comment by achchu93** [comment]
@jeffpaul Hey, I have completed all the functional tasks. Now we have left only the styling part. I can take a look at this start of next week if you allow me.

**Comment by jeffpaul** [comment]
FYI, potentially related: [Extending the Query Loop block](https://make.wordpress.org/core/2022/10/10/extending-the-query-loop-block/) dev note from WP 6.1.

**Comment by jeffpaul** [comment]
@achchu93 could you please push up a branch or PR of your work, even if it's still in-progress?

**Comment by mehul0810** [comment]
I have created a PR to add a block pattern for podcast grid. Let me know if there are any changes. Thanks!

CC: @jeffpaul
